### ISSUE TITLE
Naming convention of axis in dataset.Dataset.add_error_source()

### ISSUE THREAD

**Issue by Phylex** [dsavoiu/kafe#3]
Hi, could it be possible to change the naming convention of the axis to integers to make iterating over them automatically possible without a translating dictionary.

**Comment by dsavoiu** [comment]
Hi, this should already work as described. 

Any `axis` argument to the methods of `dataset.Dataset` can either be the string alias for the axis (`'x'` and `'y'`) or the corresponding integer (`0` and `1`, respectively). The method `dataset.Dataset.get_axis()` accepts both axis specifications and returns the integer representation.

That is: `add_error_source(1, 'simple', 0.5)` is equivalent to `add_error_source('y', 'simple', 0.5)`.

It's true that the documentation doesn't mention this explicitly. I'll leave this issue open until I can get around to correcting this...

Edit: this issue has been resolved in development. This will be reflected in the next release.
